### ISSUE TITLE
Partclone 0.3.17 fails to build on RHEL/CentOS 7 due to undefined reference to `__fpclassifyf'

### ISSUE THREAD

**Issue by robert-scheck** [Thomas-Tsai/partclone#153]
Partclone 0.3.17 fails to build on RHEL/CentOS 7, while it works on newer distributions such as RHEL/CentOS 8:

```
…
gcc -DRESTORE -DDD -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wall  -Wl,-z,relro  -o partclone.restore partclone_restore-main.o partclone_restore-partclone.o partclone_restore-progress.o partclone_restore-checksum.o partclone_restore-torrent_helper.o partclone_restore-ddclone.o  -lcrypto -lncursesw -lpthread  -ltinfo
gcc -DCHKIMG -DDD -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wall  -Wl,-z,relro  -o partclone.chkimg partclone_chkimg-main.o partclone_chkimg-partclone.o partclone_chkimg-progress.o partclone_chkimg-checksum.o partclone_chkimg-torrent_helper.o partclone_chkimg-ddclone.o  -lcrypto -lncursesw -lpthread  -ltinfo
partclone_dd-progress.o: In function `progress_init':
/builddir/build/BUILD/partclone-0.3.17/src/progress.c:50: undefined reference to `__fpclassifyf'
/builddir/build/BUILD/partclone-0.3.17/src/progress.c:50: undefined reference to `__fpclassifyf'
collect2: error: ld returned 1 exit status
make[2]: *** [partclone.dd] Error 1
…
```

It seems like this is caused by commit 536bec059c352061295b8dc7aa87f14e9c3b8d77. Setting `LDFLAGS=-lm` on RHEL/CentOS 7 myself works around the issue.

**Comment by Thomas-Tsai** [comment]
got  it, I will test and add -lm to automake
